name = "Portfolio"
license = "MIT"
licenselink = "https://github.com/mike-engel/portfolio/blob/master/themes/portfolio/LICENSE"
description = "A theme for this portfolio site"
homepage = "https://mike-engel.com/"
tags = ["personal", "portfolio"]
features = []
min_version = "0.41.0"

[author]
name = "Mike Engel"
homepage = "https://mike-engel.com"
